In [25]:
import pandas as pd
import numpy as np

In [3]:
data=pd.read_csv("data set/SalaryGender.csv")

In [4]:
data

Salary  Gender  Age  PhD
0    140.0       1   47    1
1     30.0       0   65    1
2     35.1       0   56    0
3     30.0       1   23    0
4     80.0       0   53    1
..     ...     ...  ...  ...
95    18.6       1   26    0
96   152.0       1   56    1
97     1.8       1   28    0
98    35.0       0   44    0
99     4.0       0   24    0

[100 rows x 4 columns]

### 1 Extract data from the given SalaryGender CSV file and store the data from each column in a separate NumPy array

In [5]:
Salary=np.array(data['Salary'])
Gender=np.array(data['Gender'])
Age=np.array(data['Age'])
PhD=np.array(data['PhD'])

### Find:
### 1. The number of men with a PhD
### 2. The number of women with a PhD

In [6]:
##assuming 1 in Gender as "Male"
male_count=0
female_count=0
for i in range(len(Gender)):
    
    if Gender[i]!=0 and PhD[i]!=0:
        male_count+=1
    else:
        if Gender[i]==PhD[i]:
            female_count+=1
print(" No. Male PhDn's are "+str(male_count))
print(" No. Female PhDn's are "+str(female_count))

 No. Male PhDn's are 24
 No. Female PhDn's are 35


### Use SalaryGender CSV file. Store the “Age” and “PhD” columns in one DataFrame and delete the data of all people who don’t have a PhD

In [7]:
new_data_for_age_PhD=data.drop(columns=["Gender","Salary"])
new_data_for_age_PhD.loc[(new_data_for_age_PhD!=0).any(1)]

new_data_for_age_PhD['PhD']=new_data_for_age_PhD["PhD"].replace(0,np.nan)
new_data_for_age_PhD=new_data_for_age_PhD.dropna(how='all',axis=0)

new_data_for_age_PhD

Age  PhD
0    47  1.0
1    65  1.0
2    56  NaN
3    23  NaN
4    53  1.0
..  ...  ...
95   26  NaN
96   56  1.0
97   28  NaN
98   44  NaN
99   24  NaN

[100 rows x 2 columns]

### Calculate the total number of people who have a PhD degree from SalaryGender CSV file.

In [8]:
data['PhD'].sum()


39

### How do you Count The Number Of Times Each Value Appears In An Array Of Integers?

In [9]:
def cnt(arr):
    count=np.array([0,0,0,0,0,0,0,0,0,0])
    
    for i in arr:
        
        if i==0:
            count[0]+=1
        elif i==1:
            count[1]+=1
        elif i==2:
            count[2]+=1
        elif i==3:
            count[3]+=1
        elif i==4:
            count[4]+=1
        elif i==5:
            count[5]+=1
        elif i==6:
            count[6]+=1
        elif i==7:
            count[7]+=1
        elif i==8:
            count[8]+=1
        elif i==9:
            count[9]+=1
    return count

In [10]:
a=np.array([0, 5, 4, 0, 4, 4, 3, 0, 0, 5, 2, 1, 1, 9])
cnt(a)

array([4, 2, 1, 1, 3, 2, 0, 0, 0, 1])

### Create a numpy array [[0, 1, 2], [ 3, 4, 5], [ 6, 7, 8],[ 9, 10, 11]]) and filter the elements greater than 5.

In [11]:
arr_2d=np.array([[0, 1, 2], [ 3, 4, 5], [ 6, 7, 8],[ 9, 10, 11]])

for i in arr_2d:
    for j in i:
        if j>5:
            print("vlaues greater than 5 is " +str(j))

vlaues greater than 5 is 6
vlaues greater than 5 is 7
vlaues greater than 5 is 8
vlaues greater than 5 is 9
vlaues greater than 5 is 10
vlaues greater than 5 is 11


### Create a numpy array having NaN (Not a Number) and print it.

In [12]:
nan_arr=np.array([np.nan,1,2,np.nan,3,4,5])
nan_arr

array([nan,  1.,  2., nan,  3.,  4.,  5.])

In [13]:
nan_arr=nan_arr[~np.isnan(nan_arr)]

In [14]:
nan_arr

array([1., 2., 3., 4., 5.])

### Create a 10x10 array with random values and find the minimum and maximum values.

In [15]:
x = np.int32(np.random.random((10,10))*10)
print("Original Array:")
print(x) 
xmin, xmax = x.min(), x.max()
print("Minimum and Maximum Values:")
print(xmin, xmax)

Original Array:
[[6 2 3 3 1 8 0 3 4 8]
 [3 9 0 1 2 8 0 9 1 9]
 [9 1 6 5 4 1 5 2 6 1]
 [2 6 9 0 0 5 2 2 0 9]
 [8 9 6 8 1 1 0 4 7 6]
 [7 8 1 3 7 2 1 2 6 2]
 [9 3 9 2 2 0 9 8 9 8]
 [4 9 1 5 4 7 5 0 3 3]
 [5 2 0 9 9 4 8 5 3 2]
 [7 1 8 5 9 3 2 1 4 0]]
Minimum and Maximum Values:
0 9


### Create a random vector of size 30 and find the mean value.

In [16]:
x = np.int32(np.random.random(30)*10)
print(x)
print("Mean") 
x.mean()

[6 3 3 1 9 9 8 1 7 2 6 3 7 9 2 4 9 9 6 3 3 8 3 1 1 1 5 5 7 9]
Mean


5.0

### Create numpy array having elements 0 to 10 And negate all the elements between 3 and 9

In [17]:
x=np.arange(11)
print(x[3:10])

[3 4 5 6 7 8 9]


### Create a random array of 3 rows and 3 columns and sort it according to 1st column, 2nd column or 3rd column.

In [18]:
x = np.int32(np.random.random((3,3))*10)
x=np.sort(x) # x.sort()
print(x)

[[0 5 8]
 [4 4 6]
 [4 5 6]]


### Create a four dimensions array get sum over the last two axis at once.

In [19]:
x = np.int32(np.random.random((3,3,3,3))*10)
x

array([[[[7, 0, 1],
         [1, 3, 6],
         [1, 9, 1]],

        [[4, 6, 2],
         [8, 0, 7],
         [1, 1, 5]],

        [[2, 0, 6],
         [9, 0, 8],
         [7, 6, 6]]],


       [[[8, 9, 6],
         [5, 7, 7],
         [5, 2, 9]],

        [[7, 2, 9],
         [6, 1, 5],
         [6, 6, 1]],

        [[3, 6, 0],
         [0, 8, 7],
         [5, 1, 1]]],


       [[[3, 5, 6],
         [4, 5, 7],
         [4, 1, 5]],

        [[1, 4, 3],
         [8, 9, 4],
         [5, 8, 8]],

        [[7, 3, 1],
         [4, 2, 9],
         [5, 9, 8]]]])

In [20]:
x.sum(axis=2)

array([[[ 9, 12,  8],
        [13,  7, 14],
        [18,  6, 20]],

       [[18, 18, 22],
        [19,  9, 15],
        [ 8, 15,  8]],

       [[11, 11, 18],
        [14, 21, 15],
        [16, 14, 18]]])

### Create a random array and swap two rows of an array.

In [21]:
n = np.random.rand(3,3)
n[[0, 2]] = n[[2, 0]]
n

array([[0.31238413, 0.02831381, 0.40038725],
       [0.43067765, 0.81918452, 0.41501036],
       [0.51319748, 0.51486871, 0.53439408]])

### Create a random matrix and Compute a matrix rank.

In [22]:
np.linalg.matrix_rank(n)

3

### 15.)

In [26]:
school_data = pd.read_csv("data set/middle_tn_schools.csv")

In [27]:
school_data.head()

name  school_rating   size  reduced_lunch  \
0  Allendale Elementary School            5.0  851.0           10.0   
1          Anderson Elementary            2.0  412.0           71.0   
2             Avoca Elementary            4.0  482.0           43.0   
3                Bailey Middle            0.0  394.0           91.0   
4          Barfield Elementary            4.0  948.0           26.0   

   state_percentile_16  state_percentile_15  stu_teach_ratio    school_type  \
0                 90.2                 95.8             15.7         Public   
1                 32.8                 37.3             12.8         Public   
2                 78.4                 83.6             16.6         Public   
3                  1.6                  1.0             13.1  Public Magnet   
4                 85.3                 89.2             14.8         Public   

   avg_score_15  avg_score_16  full_time_teachers  percent_black  \
0          89.4          85.2                54.0            2.9   
1          43.0          38.3                32.0            3.9   
2          75.7          73.0                29.0            1.0   
3           2.1           4.4                30.0           80.7   
4          81.3          79.6                64.0           11.8   

   percent_white  percent_asian  percent_hispanic  
0           85.5            1.6               5.6  
1           86.7            1.0               4.9  
2           91.5            1.2               4.4  
3           11.7            2.3               4.3  
4           71.2            7.1               6.0

In [29]:
school_data.head()

name  school_rating   size  reduced_lunch  \
0  Allendale Elementary School            5.0  851.0           10.0   
1          Anderson Elementary            2.0  412.0           71.0   
2             Avoca Elementary            4.0  482.0           43.0   
3                Bailey Middle            0.0  394.0           91.0   
4          Barfield Elementary            4.0  948.0           26.0   

   state_percentile_16  state_percentile_15  stu_teach_ratio    school_type  \
0                 90.2                 95.8             15.7         Public   
1                 32.8                 37.3             12.8         Public   
2                 78.4                 83.6             16.6         Public   
3                  1.6                  1.0             13.1  Public Magnet   
4                 85.3                 89.2             14.8         Public   

   avg_score_15  avg_score_16  full_time_teachers  percent_black  \
0          89.4          85.2                54.0            2.9   
1          43.0          38.3                32.0            3.9   
2          75.7          73.0                29.0            1.0   
3           2.1           4.4                30.0           80.7   
4          81.3          79.6                64.0           11.8   

   percent_white  percent_asian  percent_hispanic  
0           85.5            1.6               5.6  
1           86.7            1.0               4.9  
2           91.5            1.2               4.4  
3           11.7            2.3               4.3  
4           71.2            7.1               6.0

In [30]:
school_data.describe()

school_rating         size  reduced_lunch  state_percentile_16  \
count     347.000000   347.000000     347.000000           347.000000   
mean        2.968300   699.472622      50.279539            58.801729   
std         1.690377   400.598636      25.480236            32.540747   
min         0.000000    53.000000       2.000000             0.200000   
25%         2.000000   420.500000      30.000000            30.950000   
50%         3.000000   595.000000      51.000000            66.400000   
75%         4.000000   851.000000      71.500000            88.000000   
max         5.000000  2314.000000      98.000000            99.800000   

       state_percentile_15  stu_teach_ratio  avg_score_15  avg_score_16  \
count           341.000000       347.000000    341.000000    347.000000   
mean             58.249267        15.461671     57.004692     57.049856   
std              32.702630         5.725170     26.696450     27.968974   
min               0.600000         4.700000      1.500000      0.100000   
25%              27.100000        13.700000     37.600000     37.000000   
50%              65.800000        15.000000     61.800000     60.700000   
75%              88.600000        16.700000     79.600000     80.250000   
max              99.800000       111.000000     99.000000     98.900000   

       full_time_teachers  percent_black  percent_white  percent_asian  \
count          347.000000     347.000000     347.000000     347.000000   
mean            44.939481      21.197983      61.673487       2.642651   
std             22.053386      23.562538      27.274859       3.109629   
min              2.000000       0.000000       1.100000       0.000000   
25%             30.000000       3.600000      40.600000       0.750000   
50%             40.000000      13.500000      68.700000       1.600000   
75%             54.000000      28.350000      85.950000       3.100000   
max            140.000000      97.400000      99.700000      21.100000   

       percent_hispanic  
count        347.000000  
mean          11.164553  
std           12.030608  
min            0.000000  
25%            3.800000  
50%            6.400000  
75%           13.800000  
max           65.200000

In [62]:
school_rating=school_data.groupby('school_rating')
school_rating.first()

name   size  reduced_lunch  \
school_rating                                                      
0.0                        Pearl-Cohn High  905.0           89.0   
1.0               Whitthorne Middle School  948.0           65.0   
2.0                           Croft Middle  723.0           74.0   
3.0                   Northeast Elementary  854.0           38.0   
4.0             Westwood Elementary School  550.0           40.0   
5.0            Allendale Elementary School  851.0           10.0   

               state_percentile_16  state_percentile_15  stu_teach_ratio  \
school_rating                                                              
0.0                            3.7                  3.3             15.0   
1.0                           26.3                 26.8             17.2   
2.0                           32.0                 30.5             18.5   
3.0                           60.6                 55.4             14.4   
4.0                           77.3                 87.4             14.1   
5.0                           90.2                 95.8             15.7   

                 school_type  avg_score_15  avg_score_16  full_time_teachers  \
school_rating                                                                  
0.0            Public Magnet          12.4           8.3                60.0   
1.0                   Public          37.0          35.0                55.0   
2.0            Public Magnet          39.6          37.9                39.0   
3.0                   Public          54.2          57.6                59.0   
4.0                   Public          79.6          72.3                39.0   
5.0                   Public          89.4          85.2                54.0   

               percent_black  percent_white  percent_asian  percent_hispanic  
school_rating                                                                 
0.0                     89.0            4.9            0.4               4.5  
1.0                     22.4           61.7            1.7              14.1  
2.0                     22.0           39.4            6.2              32.1  
3.0                     22.0           50.6            1.8              15.0  
4.0                      2.7           89.1            0.9               4.0  
5.0                      2.9           85.5            1.6               5.6

In [67]:
school_data.groupby('school_rating').corr()

size  reduced_lunch  \
school_rating                                                
0.0           size                 1.000000       0.082159   
              reduced_lunch        0.082159       1.000000   
              state_percentile_16  0.246268      -0.179888   
              state_percentile_15 -0.038198      -0.408495   
              stu_teach_ratio      0.617095      -0.091060   
...                                     ...            ...   
5.0           full_time_teachers   0.968614      -0.096318   
              percent_black       -0.161495       0.685431   
              percent_white        0.163266      -0.679983   
              percent_asian        0.052812      -0.251101   
              percent_hispanic    -0.195351       0.618839   

                                   state_percentile_16  state_percentile_15  \
school_rating                                                                 
0.0           size                            0.246268            -0.038198   
              reduced_lunch                  -0.179888            -0.408495   
              state_percentile_16             1.000000             0.534677   
              state_percentile_15             0.534677             1.000000   
              stu_teach_ratio                 0.254465             0.233693   
...                                                ...                  ...   
5.0           full_time_teachers              0.032526             0.079612   
              percent_black                  -0.216945            -0.336749   
              percent_white                   0.200342             0.236087   
              percent_asian                   0.234986             0.287444   
              percent_hispanic               -0.228654            -0.165969   

                                   stu_teach_ratio  avg_score_15  \
school_rating                                                      
0.0           size                        0.617095      0.075593   
              reduced_lunch              -0.091060     -0.405721   
              state_percentile_16         0.254465      0.569705   
              state_percentile_15         0.233693      0.971201   
              stu_teach_ratio             1.000000      0.345823   
...                                            ...           ...   
5.0           full_time_teachers         -0.188878     -0.112521   
              percent_black              -0.002113     -0.346943   
              percent_white               0.051201      0.236050   
              percent_asian              -0.065868      0.314938   
              percent_hispanic           -0.123240     -0.159405   

                                   avg_score_16  full_time_teachers  \
school_rating                                                         
0.0           size                     0.288926            0.952091   
              reduced_lunch           -0.184188            0.126613   
              state_percentile_16      0.975739            0.226693   
              state_percentile_15      0.536100           -0.111845   
              stu_teach_ratio          0.313217            0.385754   
...                                         ...                 ...   
5.0           full_time_teachers      -0.147456            1.000000   
              percent_black           -0.266585           -0.173483   
              percent_white            0.206104            0.162707   
              percent_asian            0.303311            0.035191   
              percent_hispanic        -0.189623           -0.143749   

                                   percent_black  percent_white  \
school_rating                                                     
0.0           size                     -0.456726       0.203206   
              reduced_lunch            -0.047409      -0.347191   
              state_percentile_16      -0.192650       0.284667   
              state_percentile_15      -0.299026       0.583

In [68]:
df1=school_rating['school_rating']


AttributeError: 'SeriesGroupBy' object has no attribute 'corrwith'